create table "public"."central" (
    "id" bigint generated by default as identity not null,
    "room_id" bigint not null,
    "name" text not null,
    "description" text not null,
    "url" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now()
);

comment on table "public"."central" is 'Table containing the models of the processors in use.';

alter table "public"."central" enable row level security;

CREATE UNIQUE INDEX central_pkey ON public.central USING btree (id);

alter table "public"."central" add constraint "central_pkey" PRIMARY KEY using index "central_pkey";

alter table "public"."central" add constraint "central_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."rooms" ("id") ON DELETE CASCADE not valid;

alter table "public"."central" add constraint "central_url_key" UNIQUE (url); 

grant delete on table "public"."central" to "anon";

grant insert on table "public"."central" to "anon";

grant references on table "public"."central" to "anon";

grant select on table "public"."central" to "anon";

grant trigger on table "public"."central" to "anon";

grant truncate on table "public"."central" to "anon";

grant update on table "public"."central" to "anon";

grant delete on table "public"."central" to "authenticated";

grant insert on table "public"."central" to "authenticated";

grant references on table "public"."central" to "authenticated";

grant select on table "public"."central" to "authenticated";

grant trigger on table "public"."central" to "authenticated";

grant truncate on table "public"."central" to "authenticated";

grant update on table "public"."central" to "authenticated";

grant delete on table "public"."central" to "service_role";

grant insert on table "public"."central" to "service_role";

grant references on table "public"."central" to "service_role";

grant select on table "public"."central" to "service_role";

grant trigger on table "public"."central" to "service_role";

grant truncate on table "public"."central" to "service_role";

grant update on table "public"."central" to "service_role";

--------------------------------------------------------
-- Policies
--------------------------------------------------------



--------------------------------------------------------
-- Functions & Triggers
--------------------------------------------------------
