#pragma once

#define TURN_ON_BUILTIN_LED() digitalWrite(LED_BUILTIN, HIGH)
#define TURN_OFF_BUILTIN_LED() digitalWrite(LED_BUILTIN, LOW)

#define TURN_ON_GPIO_LED(LED) digitalWrite(LED, LOW)
#define TURN_OFF_GPIO_LED(LED) digitalWrite(LED, HIGH)

#define TURN_ON_BLUE_LED() TURN_ON_GPIO_LED(LED_BLUE)
#define TURN_ON_RED_LED() TURN_ON_GPIO_LED(LED_RED)
#define TURN_ON_GREEN_LED() TURN_ON_GPIO_LED(LED_GREEN)

#define TURN_OFF_BLUE_LED() TURN_OFF_GPIO_LED(LED_BLUE)
#define TURN_OFF_RED_LED() TURN_OFF_GPIO_LED(LED_RED)
#define TURN_OFF_GREEN_LED() TURN_OFF_GPIO_LED(LED_GREEN)

#define SWITCH_LED(LED) digitalWrite(LED, !digitalRead(LED))