ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine3.19

USER root

EXPOSE 3000

WORKDIR /app

COPY . .

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

CMD [ "npm", "run", "dev" ]