ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine3.19

ENV NODE_ENV=production

WORKDIR /app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

USER root

COPY --chown=root:root . .

EXPOSE 3000

RUN npm run build

CMD [ "node", "build" ]